baseURL = "https://s-brands.onrender.com/"
languageCode = "en-us"
summaryLength = "10"
theme = "icelab-hugo"
title = "Icelab Studio"
[permalinks]
"/" = "/:slug/"
page = "/:slug/"
posts = "/:slug/"
[markup.goldmark.renderer]
unsafe = true
[outputs]
home = ["HTML", "RSS"]
[params]
author = "Themefisher"
contact_form_action = "#"
description = "This is meta description"
footer_content = "Lorem ipsum dolor sit amet consectetur adipisicing elit. Doloribus sint magnam quia doloremque."
home = "Home"
logo = "images/logo.png"
[params.map]
enable = true
gmap_api = "https://maps.googleapis.com/maps/api/js?key=AIzaSyBu5nZKbeK-WHQ70oqOWo-_4VmwOwKP9YQ"
map_latitude = "51.5223477"
map_longitude = "-0.1622023"
map_marker = "images/marker.png"
[[params.plugins.js]]
URL = "plugins/plugins.js"

